### ISSUE TITLE
Crashes under Windows Vista 32 bit

### ISSUE THREAD

**Issue by userse31** [TheOnlyLordVirus/Better-Craft-Minecraft-Mod-Tool-PS3#3]
What a ridiculous idea. Running modern windows 10 era software under windows vista on a pentium m laptop. Man, you'd have to be SUPER autistic to think that's a good idea! /s

Under the 32bit version of Windows Vista (On a Pentium M) while "Better Craft" does open AND attach, attempting to enter the "Mods" menu crashes the program when using "PS3API".

There is also the occasional sound glitch when reselecting "PS3API".

----

You know, not all of us daily drive modern Windows (God I hate Windows 10) so a linux version would be appreciated.

Perhaps porting Visual studio code to debian isn't _too_ difficult, I should try that.

**Comment by TheOnlyLordVirus** [comment]
> What a ridiculous idea. Running modern windows 10 era software under windows vista on a pentium m laptop. Man, you'd have to be SUPER autistic to think that's a good idea! /s
> 
> Under the 32bit version of Windows Vista (On a Pentium M) while "Better Craft" does open AND attach, attempting to enter the "Mods" menu crashes the program when using "PS3API".
> 
> There is also the occasional sound glitch when reselecting "PS3API".
> 
> You know, not all of us daily drive modern Windows (God I hate Windows 10) so a linux version would be appreciated.
> 
> Perhaps porting Visual studio code to debian isn't _too_ difficult, I should try that.

I really do wish it just worked for you on this configuration, I feel like you may have better results if you use CCAPI or TMAPI if your console and PC are capable of it. I wouldn't mind creating a Linux version in the future but doesn't seem likely in the next 6 months.
